= Time series forecasting
:hardbreaks-option:

Time series forecasting is data analysis that enables predicting future values based on previously observed values.

== Introduction

.Time series:
Time series data is widely used for forecasting, trend analysis, and anomaly detection.
A time series is a sequence of data points recorded or measured at successive points in time.

.Timeseries characteristics:
* Trend: long-term movement in the data
* Seasonality: periodic fluctuations that occur at regular intervals (weekly, monthly, yearly, etc)
* Noise and Cyclic Patterns: random variations or Irregular/Residual

.Timeseries Visualization Techniques:
Use plots or tools like Grafana widgets to show charts in the form of lin, bar, heatmaps, etc

.Timeseries Pre-processing:
* Data Cleaning: 
** handle missing data with filling techniques: forward/backward-fill, K-nearest Neighbors
** outliers: remove or adjust outliers.
Techniques: spikes capping/smoothing/imputation, Z-scores, Interquartile Range or IQR
* Resampling & Aggregation: group/fix frequencies (upsampling/downsampling)
* Normalization: scaling data for better model performance and predictive accuracy.
Techniques: Min-Max scaling, Z-score normalization

.Time Series Analysis and Decomposition
Technique(s) used to decompose a Timeseries into its *components*.

.Stationary Concept:
A time series is considered stationary if its statistical properties—mean, variance, and autocorrelation—remain constant over time.
Tests required to apply any forecasting study.
* Stationarity Tests:
** ADF (Augmented Dickey-Fuller)
** KPSS (Kwiatkowski-Phillips-Schmidt-Shin)
* Transforming data to stationary: techniques exists to go from non-stationary to stationary

.Time Series Forecasting
* Algorithms:
** AR: Autoregression
** MA: Moving Average
** Autoregressive Integrated Moving Average (ARMA):
Helps to identify patterns within the data. Best for non=stationary.
** ARIMA:
** SARIMA:
** Exponential Smoothing Methods:
** Prohet:
** LSTM:

.Time Series Forecasts Evaluating
Techniques are used to:
* measure performance of Forecasting: MAE (Mean Absolute Error), RMSE (Root Mean Squared Error), MAPE (Mean Absolute Percentage Error)
* do time-aware cross-validation: Rolling Forecast Origin, TimeSeriesSplit

.Time Series Libraries
* Python - statsmodels
* Python - prophet
* Python - pmdarima
* Python - tsfresh

.Time Series in Machine Learning
Machine Learning methods offer greater flexibility in modeling non-linear patterns and interactions.
*supervised learning* is used where past observations are used to predict future values.
Models do not require stationarity or assumptions about the data’s structure.
* Popular Models: Random Forest (RF) and XGBoost


== Examples = Getting Data

=== Example - Prometheus Query

TIP: Below is a basic example of querying Prometheus (Victoria Metrics in reality) to extract data usable later in forecasting.

.Extracting Prometheus Time series
[source, bash]
----
$ git clone https://github.com/dcoles/prometheus-pandas.git
$ docker run -it --rm -v $(pwd):/project --network ti-dhome_default python:3 bash
root@13c29e782c6b:/project# cd /project
root@13c29e782c6b:/project# pip install -r requirements.txt
root@13c29e782c6b:/project# python 
Python 3.11.1 (main, Jan 11 2023, 14:15:54) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from prometheus_pandas import query
>>> p = query.Prometheus('http://victoriametrics:8428')
>>> series = p.query('sensors_zigbee_energy_l1{location="C01~Garage~PowerMeter",db="sensors"}[1d]', '2025-03-10T00:00:00Z')
>>> print(series)
                               sensors_zigbee_energy_l1{db="sensors",location="C01~Garage~PowerMeter"}
2025-03-09 00:00:05.108999968                                           4388.999                      
2025-03-09 00:00:05.124000072                                           4388.999                      
2025-03-09 00:00:05.947999954                                           4389.013                      
2025-03-09 00:00:05.957000017                                           4389.013                      
2025-03-09 00:00:06.947000027                                           4389.013                      
...                                                                          ...                      
2025-03-09 23:59:35.961999893                                           4397.216                      
2025-03-09 23:59:36.905999899                                           4397.216                      
2025-03-09 23:59:36.911000013                                           4397.216                      
2025-03-09 23:59:37.770999908                                           4397.216                      
2025-03-09 23:59:37.776000023                                           4397.216                      

[36258 rows x 1 columns]


>>> dataframe = p.query_range(
...         'sensors_zigbee_energy_b{location="C03~Garage~PowerMeter"}[1d]',
...         '2025-03-10T00:00:00Z', '2025-04-10T06:00:00Z', '1d')
>>> print(dataframe)
            sensors_zigbee_energy_b{db="sensors",location="C03~Garage~PowerMeter"}
2025-03-10                                            4510.96                     
2025-03-11                                            4519.74                     
2025-03-12                                            4526.50                     
2025-03-13                                            4534.09                     
2025-03-14                                            4556.59                     
2025-03-15                                            4576.35                     
2025-03-16                                            4586.18                     
2025-03-17                                            4601.75                     
2025-03-18                                            4621.40                     
2025-03-19                                            4636.10                     
2025-03-20                                            4645.50                     
2025-03-21                                            4663.49                     
2025-03-22                                            4682.31                     
2025-03-23                                            4691.22                     
2025-03-24                                            4701.79                     
2025-03-25                                            4711.21                     
2025-03-26                                            4727.84                     
2025-03-27                                            4746.99                     
2025-03-28                                            4753.54                     
2025-03-29                                            4771.46                     
2025-03-30                                            4787.84                     
2025-03-31                                            4797.15                     
2025-04-01                                            4804.08                     
2025-04-02                                            4824.13                     
2025-04-03                                            4841.53                     
2025-04-04                                            4847.65                     
2025-04-05                                            4853.89                     
2025-04-06                                            4875.21                     
2025-04-07                                            4894.73                     
2025-04-08                                            4900.80                     
2025-04-09                                            4906.08                     
2025-04-10                                            4911.21 
----

== References

.Guides
* link:https://medium.com/@wainaina.pierre/the-complete-guide-to-time-series-forecasting-models-ef9c8cd40037[Medium Article - Complete Guide to Time Series forecasting]

.Prometheus
* link:https://github.com/dcoles/prometheus-pandas[Prometheus - Pandas]